site_name: "Parallel: Concurrency without headaches"
theme:
  name: 'material'
  palette:
    primary: 'blue-grey'
    accent: 'blue-grey'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

markdown_extensions:
  - admonition
  - codehilite
  - footnotes

# nav:
#   - 'Parallel': 'index.md'
#   - 'Quickstart': 'quickstart.md'